name: pet-supervisor test build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: ./build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: supervisor-artifact
        path: build/bin/pet-supervisor
        compression-level: 9
